### ISSUE TITLE
Use internal IR CN

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-aio#51]
Unfortunately we can't do it right now because current AIO setup depends on magic chain dumps that technically can be used, but will require some workarounds to process the chain with NeoGo first and start NeoFS IR afterwards. Not worth the trouble for now, we can wait for nspcc-dev/neofs-node#2195.

**Comment by cthulhu-rider** [comment]
seems like we may start experiments

**Comment by smallhive** [comment]
Fast fix for using multisig accounts #69

**Comment by roman-khimov** [comment]
Draft, yes, but we still need a release to integrate it properly. In fact, I have a local branch that does a part of the job.
