### ISSUE TITLE
AIO doesn't start without providing envs for REST gate

### ISSUE THREAD

**Issue by smallhive** [nspcc-dev/neofs-aio#56]
During the [task](https://github.com/nspcc-dev/neofs-rest-gw/pull/93/files/19493c7a610eda80d16a194d82f48701155d732b#diff-b60176d254e63cced069dd4761c8780e1f64acd8249ed69d3bf548921e0f0be6) we've found, the last versions AIO container (0.36.0, 0.36.1) don't start without providing extra env parameters:
```
docker run --env-file ./rest-gw/rest.env nspccdev/neofs-aio:0.36.0
```

Expected behavior/start case like:
```
docker run nspccdev/neofs-aio:0.36.0
```

**Comment by roman-khimov** [comment]
Same thing with HTTP btw. We should have these defaults embedded right into the container itself.
