### ISSUE TITLE
Revise GH workflow

### ISSUE THREAD

**Issue by smallhive** [nspcc-dev/neofs-aio#67]
We need to revise current repo workflows connected with docker images

## Current Behavior
Each push make a new docker version and pushes it to DockerHub

## Expected Behavior
Push new images only on release

## Possible Solution
Update workflow

**Comment by roman-khimov** [comment]
The problem is exactly that it's _not_ a Github action. It's buried deeply in Jenkins pipelines.

**Comment by smallhive** [comment]
Whoops, one will detect this when starting to work on the issue

**Comment by roman-khimov** [comment]
In fact it's a nice issue to rework this flow into GH action.
